image: node:latest

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rm -rf public
  artifacts:
    paths:
      - styleguide
  only:
    - development
